"""create tables

Revision ID: 61f0baabfbef
Revises: 
Create Date: 2026-02-15 23:45:59.991304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61f0baabfbef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('fullname', sa.String(length=50), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('stripeCustomerID', sa.String(length=255), nullable=True),
    sa.Column('stripeSuscriptionID', sa.String(length=255), nullable=True),
    sa.Column('stripeStatus', sa.String(length=255), nullable=True),
    sa.Column('dayCount', sa.Integer(), nullable=False),
    sa.Column('dayBegin', sa.Date(), nullable=True),
    sa.Column('monthCount', sa.Integer(), nullable=False),
    sa.Column('monthStart', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('c_name', sa.String(length=20), nullable=False),
    sa.Column('c_class', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp_total', sa.Integer(), nullable=False),
    sa.Column('xpforlevel', sa.Integer(), nullable=False),
    sa.Column('lastdateactive', sa.Date(), nullable=True),
    sa.Column('dailystreak', sa.Integer(), nullable=False),
    sa.Column('beststreak', sa.Integer(), nullable=False),
    sa.Column('activedaystotal', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('chat_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_session_user_id'), ['user_id'], unique=False)

    op.create_table('task_top_term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_term', sa.String(length=500), nullable=False),
    sa.Column('task_score', sa.Float(), nullable=False),
    sa.Column('task_computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('task_version', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'task_term', 'task_version', name='uq_tasktopterm_user_task_term_task_version')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=20), nullable=False),
    sa.Column('task_id', sa.String(length=20), nullable=False),
    sa.Column('task_category', sa.String(length=20), nullable=False),
    sa.Column('task_status', sa.String(length=20), nullable=False),
    sa.Column('task_priority', sa.String(length=20), nullable=False),
    sa.Column('task_description', sa.String(length=300), nullable=False),
    sa.Column('task_location', sa.String(length=20), nullable=False),
    sa.Column('task_due_date_entered', sa.String(length=20), nullable=False),
    sa.Column('task_reminder_status', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_date_created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'task_id', name='uq_tasks_user_task_id'),
    sa.UniqueConstraint('user_id', 'task_name', name='uq_tasks_user_task_name')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    op.create_table('sub_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subtask_name', sa.String(length=20), nullable=False),
    sa.Column('subtask_id', sa.String(length=20), nullable=False),
    sa.Column('subtask_category', sa.String(length=20), nullable=False),
    sa.Column('subtask_status', sa.String(length=20), nullable=False),
    sa.Column('subtask_priority', sa.String(length=20), nullable=False),
    sa.Column('subtask_description', sa.String(length=300), nullable=False),
    sa.Column('subtask_location', sa.String(length=20), nullable=False),
    sa.Column('subtask_due_date_entered', sa.String(length=20), nullable=False),
    sa.Column('subtask_reminder_status', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('subtask_date_created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'subtask_id', name='uq_subtasks_user_subtask_id'),
    sa.UniqueConstraint('user_id', 'subtask_name', name='uq_subtasks_user_subtask_name')
    )
    op.create_table('xpstat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('c_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['c_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('xpstat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_xpstat_c_id'), ['c_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xpstat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_xpstat_c_id'))

    op.drop_table('xpstat')
    op.drop_table('sub_tasks')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))

    op.drop_table('chat_messages')
    op.drop_table('tasks')
    op.drop_table('task_top_term')
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_session_user_id'))

    op.drop_table('chat_session')
    op.drop_table('character')
    op.drop_table('user')
    # ### end Alembic commands ###
